# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: seatly_common/contracts/payments/v1/payments.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'seatly_common/contracts/payments/v1/payments.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2seatly_common/contracts/payments/v1/payments.proto\x12\x12seatly.payments.v1\"\x94\x01\n\x14\x43reatePaymentRequest\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x14\n\x0c\x61mount_minor\x18\x03 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x05 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\t\"^\n\x15\x43reatePaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x31\n\x06status\x18\x02 \x01(\x0e\x32!.seatly.payments.v1.PaymentStatus\"?\n\x11GetPaymentRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\"\xa8\x01\n\x12GetPaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x12\n\nbooking_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x14\n\x0c\x61mount_minor\x18\x04 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x31\n\x06status\x18\x06 \x01(\x0e\x32!.seatly.payments.v1.PaymentStatus*\xa5\x01\n\rPaymentStatus\x12\x1e\n\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n\x19PAYMENT_STATUS_PROCESSING\x10\x01\x12\x1c\n\x18PAYMENT_STATUS_SUCCEEDED\x10\x02\x12\x19\n\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1c\n\x18PAYMENT_STATUS_CANCELLED\x10\x04\x32\xd3\x01\n\x0ePaymentService\x12\x64\n\rCreatePayment\x12(.seatly.payments.v1.CreatePaymentRequest\x1a).seatly.payments.v1.CreatePaymentResponse\x12[\n\nGetPayment\x12%.seatly.payments.v1.GetPaymentRequest\x1a&.seatly.payments.v1.GetPaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seatly_common.contracts.payments.v1.payments_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTSTATUS']._serialized_start=558
  _globals['_PAYMENTSTATUS']._serialized_end=723
  _globals['_CREATEPAYMENTREQUEST']._serialized_start=75
  _globals['_CREATEPAYMENTREQUEST']._serialized_end=223
  _globals['_CREATEPAYMENTRESPONSE']._serialized_start=225
  _globals['_CREATEPAYMENTRESPONSE']._serialized_end=319
  _globals['_GETPAYMENTREQUEST']._serialized_start=321
  _globals['_GETPAYMENTREQUEST']._serialized_end=384
  _globals['_GETPAYMENTRESPONSE']._serialized_start=387
  _globals['_GETPAYMENTRESPONSE']._serialized_end=555
  _globals['_PAYMENTSERVICE']._serialized_start=726
  _globals['_PAYMENTSERVICE']._serialized_end=937
# @@protoc_insertion_point(module_scope)
